version: '3'
services:

  zilla:
    image: ghcr.io/aklivity/zilla:latest
    pull_policy: always
    depends_on:
      - kafka
    ports:
      - 7114:7114
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    volumes:
      - ./zilla.yaml:/etc/zilla/zilla.yaml
    command: start -v -e

  kafka:
    image: public.ecr.aws/warpstream-labs/warpstream_agent:latest
    hostname: kafka
    pull_policy: always
    ports:
      - 8080:8080
      - 9092:9092
    environment:
      WARPSTREAM_ADVERTISED_HOSTNAME_STRATEGY: custom
      WARPSTREAM_DISCOVERY_KAFKA_HOSTNAME_OVERRIDE: kafka
    command: playground

  kafka-init:
    image: bitnami/kafka:3.2
    command:
      - "/bin/bash"
      - "-c"
      -  |
        /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic items-snapshots
    depends_on:
      - kafka
    init: true
